---
title: "hw6-data612"
author: "Jared 'Jay' Klein and Olivia Triska"
date: "10/22/2021"
output: word_document
---

```{r}
library(tidyverse)
library(dplyr)
```

1)
```{r}
setwd("/Users/jay-macbook/au-datasci/au-data-612-jk/week6/homework/")
TopColleges2019 <- read_csv("ForbesAmericasTopColleges2019.csv")
```
```{r}
head(TopColleges2019)
```
```{r}
filter(TopColleges2019, Name == "American University")
```


2a)
```{r}
colleges <- c("Howard University", "George Washington University", "American University")

TopColleges2019%>%
  select(Rank, Name)%>%
  filter(Name %in% colleges)
```

2b)
```{r}
TopColleges2019[TopColleges2019$Name %in% colleges, ]
```


3)
```{r}
TopColleges2019%>%
  select(Name, Rank)%>%
  slice(384:394)
```

4)
```{r}
TopColleges2019%>%
  select(Name, Rank)%>%
  filter(between(Rank, 384, 394))
```

5)
```{r}
RC <- read_csv("Name, Gender, Weight, Height, Age, EducationLevel
  Leon, Male, 202, 6ft0in, 30, BS
  Mary, Female, 140, 5ft4in, 28, BS
  Alice, Female, 133, 5ft7in, 34, MS
  Ralph, Male, 188, 6ft2in, 31, MS
  Brenda, Female, 176, 5ft8in, 27, BS"
)
```

```{r}
TM <- tribble(
   ~Name,    ~Gender,     ~Weight,     ~Height,    ~Age,   ~EducationLevel,
  'Leon',         'Male',         202,          '6ft0in',      30,         'BS',
  'Mary',        'Female',     140,          '5ft4in',      28,         'BS',
  'Alice',         'Female',     133,          '5ft7in',      34,         'MS',
  'Ralph',         'Male',        188,          '6ft2in',      31,        'MS',
  'Brenda',      'Female',     176,         '5ft8in',      27,         'BS',
)
```

```{r}
NL <- read_csv("Name, Gender, Weight, Height, Age, EducationLevel\nLeon, Male, 202, 6ft0in, 30, BS\nMary, Female, 140, 5ft4in, 28, BS\nAlice, Female, 133, 5ft7in, 34, MS\nRalph, Male, 188, 6ft2in, 31, MS\nBrenda, Female, 176, 5ft8in, 27, BS")
```

